apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: spawner
  annotations:
    homeroom/title: "Helm 101"
    homeroom/description: "A workshop for learning basic concepts of Helm"
spec:
  rules:
  - host: "lab-helm-101.${CLUSTER_SUBDOMAIN}"
    http:
      paths:
      - path: "/"
        backend:
          serviceName: spawner
          servicePort: 8080
